### ISSUE TITLE
Strange Menu effect with ThemePainter QT

### ISSUE THREAD

**Issue by bennettpeter** [MythTV-Themes/Steppes#3]
There is a strange effect with Steppes menus when using QT Theme Painter. The menu buttons are drawn outside the menu box. If I press "Print Screen" to save a copy, the menu corrects itself. With OpenGL Theme Painter the menu is correct. This problem has existed for years, but I am concerned because with Raspberry Pi we have to use the QT Theme Painter. I have not seen this with other themes. Do you have any idea what could be causing this? Perhaps it is not a theme issue but maybe there is a workaround?

Actually, anything that forces a redraw corrects the menu, like moving the screen, moving something in front, etc. Maybe there is something I can do to force a refresh after a menu is drawn. I will have to learn about the theming process and how it works.

Photo of screen with messed up menu -> https://drive.google.com/open?id=0B-SLdaEBcVYkTGpzYjVPbkhVRFk
Photo of screen with correct menu -> https://drive.google.com/open?id=0B-SLdaEBcVYkVkNQOVJXZ1RNam8

**Comment by jpoet** [comment]
I have noticed it myself, but has not been a high enough priority to track down.  The theme takes advantage of some 'dynamic' layouts, which the Qt painter does not handle correctly.  I assume the problem is with the painter itself, but I suppose it could be in mythuitype.cpp.

**Comment by bennettpeter** [comment]
I have fixed this in MythTV , see https://code.mythtv.org/trac/ticket/12864

**Comment by jpoet** [comment]
Thank you, Peter.
